- 데이터셋별 비용 비교용

In [60]:
import os
import pandas as pd

csv_files = [v for v in os.listdir() if v[0] == '8' and v[-4:] == '.csv']

dfs = []
for csv_file in csv_files:
    df = pd.read_csv(csv_file)

    if len(df.columns) != 2:
        continue

    df.columns = ['Name', csv_file]

    dfs.append(df)

merged_df = dfs[0]
for i in range(1, len(dfs)):
    df = dfs[i]

    merged_df = merged_df.merge(df, on='Name')

merged_df['Name'] = merged_df['Name'].apply(lambda x: x.split('\\')[-1].split('.')[0])
merged_df['SOTA'] = merged_df.drop('Name', axis=1).min(axis=1)
merged_df[['Name', '8-5_MultiKruskalRandom20PerSkipFT.csv', '8-5_KruskalRandom20PerSkipFT.csv', '8-1_siwoo_changed_30sec_OrderCoupleChecked2.csv', '8-4_MP_ver1.csv']]
# merged_df

,Name,8-5_MultiKruskalRandom20PerSkipFT.csv,8-5_KruskalRandom20PerSkipFT.csv,8-1_siwoo_changed_30sec_OrderCoupleChecked2.csv,8-4_MP_ver1.csv
0,TEST_K50_1,3641.924000,3565.908000,3632.726000,3590.480000
1,TEST_K50_2,4018.284000,3996.700000,4039.758000,4019.470000
2,TEST_K100_1,3490.218000,3466.406000,3460.855000,3460.855000
3,TEST_K100_2,3585.890000,3607.868000,3491.418000,3513.486000
4,TEST_K200_1,3256.624500,3236.956000,3253.614000,3247.763500
5,TEST_K200_2,3232.827000,3195.485500,3183.216500,3173.135500
6,STAGE1_1,3645.026000,3640.808000,3699.218000,3699.218000
7,STAGE1_2,3287.978000,3364.557000,3292.888000,3245.440000
8,STAGE1_3,3070.206000,3045.423500,3043.396500,3027.531000
9,STAGE1_4,2674.595500,2654.416500,2672.741000,2638.660000
10,STAGE1_5,2329.053667,2301.777667,2322.881667,2257.396333
11,STAGE1_6,2453.895333,2446.696667,2479.760667,2404.155333
12,STAGE1_7,3370.118000,3384.410000,3415.610000,3434.078000
13,STAGE1_8,3209.514000,3138.316000,3166.359000,3109.134000
14,STAGE1_9,3106.830000,3122.796000,3086.955500,3041.878000
15,STAGE1_10,2579.450500,2579.450500,2600.419000,2506.244000
16,STAGE1_11,2514.550000,2506.645000,2471.554000,2469.936000
17,STAGE1_12,2467.616333,2478.003000,2455.891667,2340.450000
18,STAGE1_13,4951.566000,4864.760000,4946.676000,4948.966000
19,STAGE1_14,4176.522000,4174.706000,4221.761000,4150.432000
20,STAGE1_15,4316.217000,4230.940000,4220.712000,4248.892500
21,STAGE1_16,3321.476500,3321.476500,3330.205000,3254.969000
22,STAGE1_17,3519.617333,3486.004000,3485.252667,3482.326333
23,STAGE1_18,3588.156667,3586.256000,3567.761000,3488.162000

In [52]:
# 8-1_siwoo_changed_30sec_OrderCoupleChecked2.csv,
# 8-3_bundling_opt_ver1_KruskalRandom_KCasework.csv,
# 8-4_MP_ver1.csv

In [61]:
merged_df.drop('Name', axis=1).sum().sort_values()

SOTA                                                           77855.927667
8-4_MP_ver1.csv                                                78753.058500
8-5_MP_ver1_SAFixed.csv                                        78930.134000
8-5_MP_ver1_ManySA.csv                                         79004.317500
8-4_bundling_opt_ver1_5Orders5.csv                             79012.435667
8-4_bundling_opt_ver1_5Orders3.csv                             79041.902333
8-4_bundling_opt_ver1_5Orders4.csv                             79066.099333
8-3_bundling_opt_ver1_KruskalRandom_KCasework.csv              79097.993667
8-3_bundling_opt_ver1_KruskalRandom_KCasework2.csv             79102.157667
8-4_bundling_opt_ver1_5Orders3_WalkOpt.csv                     79144.002000
8-5_MP_ver1_WeightSA_combined.csv                              79168.847333
8-3_bundling_opt_ver1_KruskalRandom.csv                        79195.786500
8-4_bundling_opt_ver1_5Orders4_WalkOpt.csv                     79218.787667
8-4_bundling_opt_ver1_5Orders5_WalkOpt.csv                     79233.319000
8-3_bundling_opt_ver1.csv                                      79388.204333
8-5_KruskalRandom20PerSkipFT.csv                               79396.765833
8-4_bundling_opt_ver1_KruskalDiverseRandom_KCasework.csv       79437.191833
8-4_bundling_opt_ver1_5Orders2.csv                             79468.044500
8-5_SA_ver4.csv                                                79523.799167
8-1_siwoo_changed_30sec_OrderCoupleChecked2.csv                79541.630167
8-5_bundling_opt_ver1_MultiKruskalRandom_KCasework.csv         79563.274333
8-5_KruskalRandom60PerSkipFT.csv                               79571.743667
8-5_KruskalRandom40PerSkipFT.csv                               79587.929667
8-5_SA_ver2.csv                                                79611.411333
8-3_bundling_opt_ver2.csv                                      79667.496333
8-3_bundling_opt_ver1_KruskalRandom_KCasework_WithoutSA.csv    79672.831000
8-1_siwoo_changed_30sec_OrderCoupleChecked.csv                 79677.218500
8-3_bundling_opt_ver2_SAReady_time.csv                         79698.247667
8-5_MultiKruskalRandom20PerSkipFT.csv                          79808.156333
8-4_bundling_opt_ver1_5Orders.csv                              79829.023833
8-5_KruskalRandom20PerSkipTF.csv                               79936.816667
8-1_siwoo_changed_30sec.csv                                    79956.591000
8-5_SA_ver5.csv                                                80055.939500
8-5_KruskalRandom20PerSkipTX.csv                               80245.975667
8-2_ch_OrderCoupleChecked.csv                                  80376.627500
8-1_siwoo_changed_20sec_edge_num_divided_by_10.csv             80391.089833
8-2_sw_OrderCoupleChecked.csv                                  80471.905500
8-5_MultiKruskalRandom20PerSkipTFAdded.csv                     80504.814333
8-1_siwoo_changed_20sec.csv                                    80566.982833
8-2_ch_base.csv                                                80606.552167
8-2_sw_base.csv                                                80634.493333
8-1_siwoo_base.csv                                             80703.667667
8-5_MultiKruskalRandom20PerSkipTF.csv                          80905.546667
8-1_siwoo_changed_30sec_SAAllBundle.csv                        80985.376333
8-5_KruskalRandom40PerSkipTF.csv                               81007.347000
8-1_siwoo_changed_10to30sec_edge_num_divided_by_10.csv         81033.689833
8-1_siwoo_changed_30sec_no_SA.csv                              81295.343667
8-1_siwoo_changed_40sec.csv                                    81584.863167
dtype: float64

In [24]:
merged_df.to_csv('result_info_0803_hyeok.csv', encoding='utf-8-sig', index=False)